project:
  type: website
# add resume and CV here 

image: ABB09310.jpg

about: 
  template: trestles
  links:
    - icon: linkedin
      href: https://www.linkedin.com/in/denis-ostroushko/
  #  - text: RPubsm
  #    href: 
    - icon: github
      href: https://github.com/denisostroushko1
    - text: Email
      href: mailto:denisostroushko1@gmail.com
    - text: Academic Email
      href: mailto:ostro233@umn.edu

website:
  page-navigation: true
  title: "Denis <br> Ostroushko"
  navbar:
    search: true
    left:
      - text: 'Resume'
        href: Denis Ostroushko Main Resume.pdf
      - sidebar:shinyapps
      - sidebar:reference_materials
      - sidebar:writing_samples
      - sidebar:fun_analysis

  sidebar:
  - id: shinyapps
    title: "My Dashboards"
    style: "docked"
    background: light
    collapse-level: 2
    contents: 
      - text: Royal FC - Amateur Soccer Team Performance 
        href: https://rpubs.com/kexite/royal_fc_knights_2023
      - text: FBref Powered Analysis of Soccer Players
        href: https://kexite.shinyapps.io/fb_ref_dashboard/
      - text: Market Analysis Dashboard 
        href: https://kexite.shinyapps.io/01_Deployment/
  - id: reference_materials
    title: "Analysis Reference Materials"
    style: "docked"
    background: light
    collapse-level: 2
    contents: 
      - text: "Introduction of Gaussian Regression in R"
        href: https://github.com/denisostroushko1/Homework-7405
      - text: "Introduction of GLM Regression in R + <br>Other Inference Topics"
        href: https://github.com/denisostroushko1/Homework-7406
      - text: "Review of GLM models + <br> Analysis of Correlated Outcomes"
        href: https://github.com/denisostroushko1/Homework-7430
      - text: "Regression Analysis for <br> Causal Inference"
        href: https://github.com/denisostroushko1/Homework-7485
      - text: "Bayesian Statistical Inference"
        href: https://github.com/denisostroushko1/Homework-7440
        
  - id: writing_samples
    title: "Writing Samples"
    style: "docked"
    background: light
    collpase-level: 2
    contents: 
      - text: "Analysis of Correlated Data <br> Using GEE Model"
        href: PubH7430_Group3_FinalReport..pdf
      - text: "Analysis of Variable Selection <br> Methods in Causal Inference <br> via a Simulation Study"
        href: Causal-Inference-Final-Paper.pdf
      - text: "Creating Study Sample for MCI-to-AD <br> progression using EHR data: <br> Masters in Biostatistics Thesis"
        href: DenisOstroushko-PlanB-Final-4-25-2024.pdf
  - id: fun_analysis
    title: "Other Fun Analyses"
    style: "docked"
    background: light
    collpase-level: 2
    contents: 
      - text: "Party Game: Ride the Bus"
        href: https://rpubs.com/kexite/riding_the_party_bus
format:
  html:
    link-external-newwindow: true
    theme: lux
    toc: false
    fontsize: 16px
    smooth-scroll: true
    page-layout: full
    margin-left: 0.5%
    margin-right: 0.5%
    
    
