project:
  type: website
  resources:
    - /Users/denisostroushko/Desktop/R/GitRepos/royal_fc_2023/Knights_2023.html
# add resume and CV here 

image: ABB09310.jpg

about: 
  template: trestles
  links:
    - icon: linkedin
      href: https://www.linkedin.com/in/denis-ostroushko/
  #  - text: RPubsm
  #    href: 
    - icon: github
      href: https://github.com/denisostroushko1
    - text: Email
      href: mailto:denisostroushko1@gmail.com
    - text: Academic Email
      href: mailto:ostro233@umn.edu

website:
  page-navigation: true
  title: "Denis Ostroushko"
  navbar:
    search: true
    left:
      - text: 'Home'
        href: index.qmd
      - text: 'Resume'
        href: Resume.pdf
      - sidebar:shinyapps
      - sidebar:reference_materials
      - sidebar:writing_samples

  sidebar:
  - id: shinyapps
    title: "My Dashboards"
    style: "docked"
    background: light
    collapse-level: 2
    contents: 
      - text: Royal FC - Amateur Soccer Team Performance 
        href: https://rpubs.com/kexite/royal_fc_knights_2023
      - text: FBref Powered Analysis of Soccer Players
        href: https://kexite.shinyapps.io/soccer_dashboard/
      - text: Market Analysis Dashboard 
        href: https://kexite.shinyapps.io/super_secret_db/
  - id: reference_materials
    title: "Analysis Reference Materials"
    style: "docked"
    background: light
    collapse-level: 2
    contents: 
      - text: "Introduction of Gaussian Regression in R"
        href: https://github.com/denisostroushko1/Homework-7405
      - text: "Introduction of GLM Regression in R + <br>Other Inference Topics"
        href: https://github.com/denisostroushko1/Homework-7406
      - text: "Review of GLM models + <br> Analysis of Correlated Outcomes"
        href: https://github.com/denisostroushko1/Homework-7430
      - text: "Regression Analysis for <br> Causal Inference"
        href: https://github.com/denisostroushko1/Homework-7485
  - id: writing_samples
    title: "Writing Samples"
    style: "docked"
    background: light
    collpase-level: 2
    contents: 
      - text: "Analysis of Correlated Data <br> Using GEE Model"
        href: PubH7430_Group3_FinalReport..pdf
      - text: "Analysis of Variable Selection <br> Methods in Causal Inference <br> via a Simulation Study"
        href: Final-Report.pdf
format:
  html:
    theme: lux
    toc: false
    smooth-scroll: true
    page-layout: full
    margin-left: 0.5%
    margin-right: 0.5%